name: fdatatable
description: a Flutter Datatable plugin.
version: 0.0.2
homepage: https://github.com/ysfgrl/fdatatable.git
repository: https://github.com/ysfgrl/fdatatable.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider:  ^6.1.2
  date_field: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: